### ISSUE TITLE
Create Account && Login

### ISSUE THREAD

**Issue by purcell3a** [howstrongiam/frontend#21]
# WEB
-----

<img width="723" alt="image" src="https://user-images.githubusercontent.com/62629855/194638019-d0e8cfd5-dad5-4867-a7fe-2c52e8a92cf6.png">

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/62629855/194638084-dc9217fc-e406-42de-b514-af9aece3ba8b.png">

# MOBILE
-----

<img width="362" alt="image" src="https://user-images.githubusercontent.com/62629855/194637856-cf96e579-88f1-4e45-9428-3bf79657c23f.png">

<img width="184" alt="image" src="https://user-images.githubusercontent.com/62629855/194637925-3d344ea8-a830-4662-8676-2b7cf71d644e.png">

**Comment by aneeqkhurram007** [comment]
Create account and login page added with mobile designs added to branch enhancement/frontend
