### ISSUE TITLE
Shop Page

### ISSUE THREAD

**Issue by purcell3a** [howstrongiam/frontend#22]
# WEB 

> 
Implement the New Landing Page Design [FIGMA LINK](https://www.figma.com/proto/Ui6fL14MnBDjyxXGrSr6Sb/Untitled?page-id=0%3A1&node-id=1%3A2&viewport=269%2C322%2C0.17&scaling=scale-down-width&starting-point-node-id=1%3A2)

> 
> [Desktop Screen Images.zip](https://github.com/howstrongiam/frontend/files/9709812/Desktop.Screen.Images.zip)
> Full file will be included with work order 

----
<img width="473" alt="image" src="https://user-images.githubusercontent.com/62629855/194638796-41fbdcae-a6bf-416f-b0bc-6612e812f5a4.png">

# MOBILE 
----
> This is the mobile design but it is **still being revised!** [FIGMA DESIGN](https://www.figma.com/proto/FKZoUeWS4kU2V5AHDcv5Zg/Mobile-Design?page-id=0%3A1&node-id=1%3A10&viewport=402%2C328%2C0.07&scaling=scale-down&starting-point-node-id=1%3A10)

> [Mobile Screen Images.zip](https://github.com/howstrongiam/frontend/files/9709819/Mobile.Screen.Images.zip)
> Full file will be included with work order 

<img width="217" alt="image" src="https://user-images.githubusercontent.com/62629855/194638861-9b0a6044-de83-48c7-ad05-bbf3fc6529b7.png">

<img width="191" alt="image" src="https://user-images.githubusercontent.com/62629855/194640194-33e1aac6-6bc4-4ef4-abd2-c7dc7ef20a5c.png">

**Comment by aneeqkhurram007** [comment]
Shop page desktop and mobile design has been added.
