### ISSUE TITLE
Profile Page -> Favorited Products

### ISSUE THREAD

**Issue by purcell3a** [howstrongiam/frontend#23]
# WEB 

> 
Implement the New Landing Page Design [FIGMA LINK](https://www.figma.com/proto/Ui6fL14MnBDjyxXGrSr6Sb/Untitled?page-id=0%3A1&node-id=1%3A2&viewport=269%2C322%2C0.17&scaling=scale-down-width&starting-point-node-id=1%3A2)

> 
> [Desktop Screen Images.zip](https://github.com/howstrongiam/frontend/files/9709812/Desktop.Screen.Images.zip)
> Full file will be included with work order 

----
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/62629855/194639303-8ba7d44f-9518-4368-ba0e-e16147b2c5c2.png">

# MOBILE 

> This is the mobile design but it is **still being revised!** [FIGMA DESIGN](https://www.figma.com/proto/FKZoUeWS4kU2V5AHDcv5Zg/Mobile-Design?page-id=0%3A1&node-id=1%3A10&viewport=402%2C328%2C0.07&scaling=scale-down&starting-point-node-id=1%3A10)

> [Mobile Screen Images.zip](https://github.com/howstrongiam/frontend/files/9709819/Mobile.Screen.Images.zip)
> Full file will be included with work order 

----
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/62629855/194639436-3ada3df7-bd56-4b46-a7ce-0c0606f37212.png">

**Comment by aneeqkhurram007** [comment]
Favorited product screens added for desktop and mobile
