### ISSUE TITLE
Company Profile 

### ISSUE THREAD

**Issue by purcell3a** [howstrongiam/frontend#25]
# WEB 

NOTE - COMPANY PROFILE WILL NOT HAVE PRODUCT REVIEWS OR PRODUCT FAVORITES TAB IT WILL INSTEAD HAVE JUST A PRODUCTS TAB AND THE ABILITY TO ADD PRODUCTS 
> 
Implement the New Landing Page Design [FIGMA LINK](https://www.figma.com/proto/Ui6fL14MnBDjyxXGrSr6Sb/Untitled?page-id=0%3A1&node-id=1%3A2&viewport=269%2C322%2C0.17&scaling=scale-down-width&starting-point-node-id=1%3A2)

> 
> [Desktop Screen Images.zip](https://github.com/howstrongiam/frontend/files/9709812/Desktop.Screen.Images.zip)
> Full file will be included with work order 

----
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/62629855/194640304-2102a46a-17c9-4af7-9426-50dbec856d0c.png">

# MOBILE 

> This is the mobile design but it is **still being revised!** [FIGMA DESIGN](https://www.figma.com/proto/FKZoUeWS4kU2V5AHDcv5Zg/Mobile-Design?page-id=0%3A1&node-id=1%3A10&viewport=402%2C328%2C0.07&scaling=scale-down&starting-point-node-id=1%3A10)

> [Mobile Screen Images.zip](https://github.com/howstrongiam/frontend/files/9709819/Mobile.Screen.Images.zip)
> Full file will be included with work order 

----
<img width="351" alt="image" src="https://user-images.githubusercontent.com/62629855/194640358-a4782014-d823-4982-9f56-5d5c4e73334e.png">

**Comment by aneeqkhurram007** [comment]
Comment page added
