### ISSUE TITLE
Profile -> added products 

### ISSUE THREAD

**Issue by purcell3a** [howstrongiam/frontend#27]
# WEB 

> 
Implement the New Landing Page Design [FIGMA LINK](https://www.figma.com/proto/Ui6fL14MnBDjyxXGrSr6Sb/Untitled?page-id=0%3A1&node-id=1%3A2&viewport=269%2C322%2C0.17&scaling=scale-down-width&starting-point-node-id=1%3A2)

> 
> [Desktop Screen Images.zip](https://github.com/howstrongiam/frontend/files/9709812/Desktop.Screen.Images.zip)
> Full file will be included with work order 

----
<img width="1417" alt="image" src="https://user-images.githubusercontent.com/62629855/194641150-38a5f5ef-54f1-4d4f-adc3-8dc4007e075e.png">

# MOBILE 

> This is the mobile design but it is **still being revised!** [FIGMA DESIGN](https://www.figma.com/proto/FKZoUeWS4kU2V5AHDcv5Zg/Mobile-Design?page-id=0%3A1&node-id=1%3A10&viewport=402%2C328%2C0.07&scaling=scale-down&starting-point-node-id=1%3A10)

> [Mobile Screen Images.zip](https://github.com/howstrongiam/frontend/files/9709819/Mobile.Screen.Images.zip)
> Full file will be included with work order 

----
<img width="323" alt="image" src="https://user-images.githubusercontent.com/62629855/194641172-ba6a2179-5ec1-4895-bfe2-152b6686da4d.png">

**Comment by aneeqkhurram007** [comment]
Added products section added to the pull request
