### ISSUE TITLE
create a tutorial for adding the endpoints 

### ISSUE THREAD

**Issue by purcell3a** [howstrongiam/frontend#61]
You'll see on this repo that you can make a wiki page 

I need a VERY simple tutorial for beginner engineers on how to add an endpoint to this project

I sent you an example of the one i have on the backend which you'll be able to view since you're on that repo now 

[EXAMPLE](https://github.com/Moral-Authority/backend/wiki/Adding-an-Endpoint)

As you can see the directions are very simple 

1. add ______ to _____ file 
and then a screenshot

2. THEN add ___ to ____ file
screenshot

and so on

**Comment by aneeqkhurram007** [comment]
Link to the Wiki: https://github.com/howstrongiam/frontend/wiki/Adding-an-Endpoint
